name: Package WordPress Plugin

on:
  push:
    tags:
      - '*'  # Triggers on all tag pushes (e.g. v1.0.0)

jobs:
  build-and-release:
    name: Zip and upload plugin
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare clean zip folder
        run: |
          mkdir beech_login
          shopt -s extglob
          cp -r !(beech_login|.git|.github) beech_login/
          zip -r beech_login.zip beech_login

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: beech_login.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}